export const OFFER_LIST_REQUEST='OFFER_LIST_REQUEST'
export const OFFER_LIST_SUCCESS='OFFER_LIST_SUCCESS'
export const OFFER_LIST_FAIL='OFFER_LIST_FAIL'
export const OFFER_LIST_RESET='OFFER_LIST_RESET'

export const OFFER_ADD_REQUEST='OFFER_ADD_REQUEST'
export const OFFER_ADD_SUCCESS='OFFER_ADD_SUCCESS'
export const OFFER_ADD_FAIL='OFFER_ADD_FAIL'
export const OFFER_ADD_RESET='OFFER_ADD_RESET'

export const OFFER_DELETE_REQUEST='OFFER_DELETE_REQUEST'
export const OFFER_DELETE_SUCCESS='OFFER_DELETE_SUCCESS'
export const OFFER_DELETE_FAIL='OFFER_DELETE_FAIL'
export const OFFER_DELETE_RESET='OFFER_DELETE_RESET'